/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package lib.robotics.rcs.server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SecurityError implements org.apache.thrift.TEnum {
  USER_NOT_LOGGED_IN(1),
  INSUFFICIENT_RIGHTS(2);

  private final int value;

  private SecurityError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SecurityError findByValue(int value) { 
    switch (value) {
      case 1:
        return USER_NOT_LOGGED_IN;
      case 2:
        return INSUFFICIENT_RIGHTS;
      default:
        return null;
    }
  }
}
