/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RobotService_H
#define RobotService_H

#include <thrift/TDispatchProcessor.h>
#include "robot_service_types.h"

namespace robot_control_system {

class RobotServiceIf {
 public:
  virtual ~RobotServiceIf() {}
  virtual void Echo(std::string& _return, const std::string& message) = 0;
};

class RobotServiceIfFactory {
 public:
  typedef RobotServiceIf Handler;

  virtual ~RobotServiceIfFactory() {}

  virtual RobotServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RobotServiceIf* /* handler */) = 0;
};

class RobotServiceIfSingletonFactory : virtual public RobotServiceIfFactory {
 public:
  RobotServiceIfSingletonFactory(const boost::shared_ptr<RobotServiceIf>& iface) : iface_(iface) {}
  virtual ~RobotServiceIfSingletonFactory() {}

  virtual RobotServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RobotServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<RobotServiceIf> iface_;
};

class RobotServiceNull : virtual public RobotServiceIf {
 public:
  virtual ~RobotServiceNull() {}
  void Echo(std::string& /* _return */, const std::string& /* message */) {
    return;
  }
};

typedef struct _RobotService_Echo_args__isset {
  _RobotService_Echo_args__isset() : message(false) {}
  bool message;
} _RobotService_Echo_args__isset;

class RobotService_Echo_args {
 public:

  RobotService_Echo_args() : message() {
  }

  virtual ~RobotService_Echo_args() throw() {}

  std::string message;

  _RobotService_Echo_args__isset __isset;

  void __set_message(const std::string& val) {
    message = val;
  }

  bool operator == (const RobotService_Echo_args & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const RobotService_Echo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RobotService_Echo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RobotService_Echo_pargs {
 public:


  virtual ~RobotService_Echo_pargs() throw() {}

  const std::string* message;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RobotService_Echo_result__isset {
  _RobotService_Echo_result__isset() : success(false) {}
  bool success;
} _RobotService_Echo_result__isset;

class RobotService_Echo_result {
 public:

  RobotService_Echo_result() : success() {
  }

  virtual ~RobotService_Echo_result() throw() {}

  std::string success;

  _RobotService_Echo_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const RobotService_Echo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RobotService_Echo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RobotService_Echo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RobotService_Echo_presult__isset {
  _RobotService_Echo_presult__isset() : success(false) {}
  bool success;
} _RobotService_Echo_presult__isset;

class RobotService_Echo_presult {
 public:


  virtual ~RobotService_Echo_presult() throw() {}

  std::string* success;

  _RobotService_Echo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RobotServiceClient : virtual public RobotServiceIf {
 public:
  RobotServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  RobotServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Echo(std::string& _return, const std::string& message);
  void send_Echo(const std::string& message);
  void recv_Echo(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RobotServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RobotServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RobotServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Echo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RobotServiceProcessor(boost::shared_ptr<RobotServiceIf> iface) :
    iface_(iface) {
    processMap_["Echo"] = &RobotServiceProcessor::process_Echo;
  }

  virtual ~RobotServiceProcessor() {}
};

class RobotServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RobotServiceProcessorFactory(const ::boost::shared_ptr< RobotServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RobotServiceIfFactory > handlerFactory_;
};

class RobotServiceMultiface : virtual public RobotServiceIf {
 public:
  RobotServiceMultiface(std::vector<boost::shared_ptr<RobotServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RobotServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RobotServiceIf> > ifaces_;
  RobotServiceMultiface() {}
  void add(boost::shared_ptr<RobotServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Echo(std::string& _return, const std::string& message) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Echo(_return, message);
    }
    ifaces_[i]->Echo(_return, message);
    return;
  }

};

} // namespace

#endif
