/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "robot_service_constants.h"

namespace robot_control_system {

const robot_serviceConstants g_robot_service_constants;

robot_serviceConstants::robot_serviceConstants() {
}

} // namespace

