/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef robot_service_CONSTANTS_H
#define robot_service_CONSTANTS_H

#include "robot_service_types.h"

namespace robot_control_system {

class robot_serviceConstants {
 public:
  robot_serviceConstants();

};

extern const robot_serviceConstants g_robot_service_constants;

} // namespace

#endif
