/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "user_service_constants.h"

namespace robot_control_system {

const user_serviceConstants g_user_service_constants;

user_serviceConstants::user_serviceConstants() {
}

} // namespace

