/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_service_CONSTANTS_H
#define user_service_CONSTANTS_H

#include "user_service_types.h"

namespace robot_control_system {

class user_serviceConstants {
 public:
  user_serviceConstants();

};

extern const user_serviceConstants g_user_service_constants;

} // namespace

#endif
