/* Robot Control System
 * Copyright (C) 2013 Tuna Oezer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef ROBOT_CONTROL_SYSTEM_THRIFT_SERVER_HPP_
#define ROBOT_CONTROL_SYSTEM_THRIFT_SERVER_HPP_

#include <type_traits>

#include "server.hpp"

namespace robot_control_system {

/**
 * Template class for all ThriftServers. Instantiates a Thrift Server for the specified handler
 * and processor types.
 *
 * The handler implementation must derive from the handler interface generated by the thrift
 * compiler. The processor type must be the corresponding TProcessor implementation generated by
 * the thrift compiler.
 *
 * For example, for the Thrift service MyService, a ThriftServer can be created with the arguments
 *     ThriftServer<MyService, MyServiceProcessor>
 * where MyService is an implementation of MyServiceIf and MyServiceProcessor is generated by the
 * thrift compiler.
 */
template<class THandler, class TProcessor>
class ThriftServer : public Server {
    NO_COPY_ASSIGN(ThriftServer);
    static_assert(::std::is_base_of<apache::thrift::TProcessor, TProcessor>::value,
        "TProcessor must be a derived class of apache::thrift::TProcessor");

  protected:
    explicit ThriftServer(const Params& params)
      : Server(params) {
    }

    virtual apache::thrift::TProcessor* CreateProcessor() {
      boost::shared_ptr<THandler> handler(new THandler());
      return new TProcessor(handler);
    }
};

}

#endif /* ROBOT_CONTROL_SYSTEM_THRIFT_SERVER_HPP_ */
